services:
  mysql:
    image: mysql:latest
    container_name: leetcode_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: leetcode
      MYSQL_USER: leetcode
      MYSQL_PASSWORD: password123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
